[package]
name = "openfga-storage-sql"
description = "SQL storage backends and migrations for OpenFGA"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
openfga-condition.workspace = true
openfga-domain.workspace = true
openfga-model.workspace = true
openfga-storage.workspace = true
opentelemetry.workspace = true
serde.workspace = true
serde_json.workspace = true
secrecy.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
typed-builder.workspace = true
ulid.workspace = true

[dev-dependencies]
openfga-storage = { workspace = true, features = ["test-support"] }
