[package]
name = "openfga-storage-dynamodb"
description = "Amazon DynamoDB storage backend for OpenFGA"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
aws-smithy-http-client.workspace = true
getrandom.workspace = true
openfga-domain.workspace = true
openfga-model.workspace = true
openfga-storage.workspace = true
opentelemetry.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
typed-builder.workspace = true
ulid.workspace = true
url.workspace = true

[dev-dependencies]
openfga-storage = { workspace = true, features = ["test-support"] }
proptest.workspace = true
ulid.workspace = true
