[package]
name = "openfga-model"
description = "Deterministic validation and compilation of OpenFGA authorization models"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
openfga-condition.workspace = true
openfga-domain.workspace = true
thiserror.workspace = true
typed-builder.workspace = true

[dev-dependencies]
proptest.workspace = true
