[package]
name = "openfga-proto"
description = "Pinned generated protobuf and gRPC types for the OpenFGA and AuthZEN v1 APIs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
pbjson.workspace = true
pbjson-types.workspace = true
prost.workspace = true
prost-reflect.workspace = true
serde.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
