[package]
name = "openfga-transport"
description = "Tonic and Axum transport adapters for OpenFGA"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
axum.workspace = true
openfga-auth.workspace = true
openfga-check.workspace = true
openfga-condition.workspace = true
openfga-domain.workspace = true
openfga-model.workspace = true
openfga-proto.workspace = true
openfga-service.workspace = true
openfga-storage.workspace = true
pbjson-types.workspace = true
prost.workspace = true
prost-reflect.workspace = true
prost-validate.workspace = true
prost-validate-types.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
typed-builder.workspace = true
ulid.workspace = true

[dev-dependencies]
async-trait.workspace = true
openfga-storage-memory.workspace = true
secrecy.workspace = true
tokio-stream.workspace = true
tracing-subscriber.workspace = true
